### ISSUE TITLE
Guide slightly incorrect

### ISSUE THREAD

**Issue by ShyMaster202** [sysce/chrome100#2]
This guide is slightly incorrect, as the name of the board is actually the last word in the **Platform:** line. 

![image](https://user-images.githubusercontent.com/88460160/198730863-56d44a72-5c51-4bb6-9ee3-31ca643e6419.png)

**Comment by e9x** [comment]
I will have to update the screenshot soon. The platform version is more reliable than the firmware.

**Comment by e9x** [comment]
Updated.
![image](https://user-images.githubusercontent.com/76465669/198773655-877db821-614b-44da-9913-4cd14eee4384.png)
